CC=gcc
CFLAGS=-O2 -Wall -Wextra -std=c99
LDFLAGS=
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Linux)
  CFLAGS += -pthread
  LDFLAGS += -pthread
else
  LDFLAGS += -lws2_32
endif

all: server
server: server.c
	$(CC) $(CFLAGS) -o server server.c $(LDFLAGS)

clean:
	rm -f server server.exe
